### Carregando Dados

In [1]:
import pandas as pd

In [7]:
X_train = pd.read_parquet('../Datasets/Split/X_train_raw.parquet')
X_test = pd.read_parquet('../Datasets/Split/X_test_raw.parquet')
y_train = pd.read_parquet('../Datasets/Split/y_train.parquet')
y_test = pd.read_parquet('../Datasets/Split/y_test.parquet')

### One Hot Encoding

In [5]:
df = pd.get_dummies(
    df,
    columns=['SG_UF'],
    drop_first=False,
    dtype=int
)

### AutoML com AutoGluon

In [11]:
from autogluon.tabular import TabularPredictor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from tqdm import tqdm
import os
import shutil

/home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [12]:
def prepare_autogluon_data(X, y, target_column):
    data = X.copy()
    data[target_column] = y.values
    return data

In [13]:
def run_automl(
    X_train,
    y_train,
    X_val,
    y_val,
    X_test,
    y_test,
    target_column,
    id_column=None,
    output_path="autogluon_regression",
    time_limit=600,
    overwrite=True
):
    if overwrite and os.path.exists(output_path):
        shutil.rmtree(output_path)

    if id_column is not None:
        X_train = X_train.drop(columns=[id_column], errors="ignore")
        X_val = X_val.drop(columns=[id_column], errors="ignore")
        X_test = X_test.drop(columns=[id_column], errors="ignore")

    train_data = prepare_autogluon_data(X_train, y_train, target_column)
    val_data = prepare_autogluon_data(X_val, y_val, target_column)

    train_full = pd.concat(
        [train_data, val_data],
        ignore_index=True
    )

    test_data = prepare_autogluon_data(X_test, y_test, target_column)

    predictor = TabularPredictor(
        label=target_column,
        problem_type="regression",
        eval_metric="root_mean_squared_error",
        path=output_path
    )

    predictor.fit(
        train_data=train_full,
        time_limit=time_limit,
        presets="best_quality"
    )

    X_test_final = test_data.drop(columns=[target_column])

    predictions = predictor.predict(X_test_final)

    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    metrics = {
        "rmse": rmse,
        "mae": mae,
        "r2": r2
    }

    leaderboard = predictor.leaderboard(
        test_data,
        silent=True
    )

    return predictor, metrics, leaderboard, predictions

In [14]:
predictor, metrics, leaderboard, predictions = run_automl(
    X_train=X_train_scaled,
    y_train=y_train,
    X_val=X_val_scaled,
    y_val=y_val,
    X_test=X_test_scaled,
    y_test=y_test,
    target_column="TAXA_CRE_INT",
    id_column="NO_MUNICIPIO",
    output_path="autogluon_regression",
    time_limit=3600
)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jun 11 01:32:26 UTC 2026
CPU Count:          16
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       8.70 GB / 15.23 GB (57.1%)
Disk Space Avail:   48.56 GB / 182.28 GB (26.6%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
2026-06-19 19:58:07,626	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-06-19 19:58:10,710	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
/home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
		Context path: "/home/guilherme_fernandes/Aprendizagem_Autom-tica_UFC_2026.1/criancas_creche/Notebooks/autogluon_regression/ds_sub_fit/sub_fit_ho"
(_dystack pid=1337) Running DyStack sub-fit ...
(_dystack pid=1337) Beginning AutoGluon training ... Time limit = 896s
(_dystack pid=1337) AutoGluon will save models to "/home/guilherme_fernandes/Aprendizagem_Autom-tica_UFC_2026.1/criancas_creche/Notebooks/autogluon_regression/ds_sub_fit/sub_fit_ho"
(_dystack pid=1337) Train Data Rows:    1265
(_dystack pid=1337) Train Data Columns: 24
(_dystack pid=1337) Label Column:       TAXA_CRE_INT
(_dystack pid=1337) Problem Type:       regression
(_dystack pid=1337) Preprocessing data ...
(_dystack pid=1337) Using Feature Generators to preprocess the data ...
(_dystack pid=1337) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=1337) 	Available Memory:                    6981.22 MB
(_dystack pid=1337) 	Train Data (Original)  Memory Usage: 0.23 MB (0.0% of available memory)
(_dystack pid=1337) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=1337) 	Stage 1 Generators:
(_dystack pid=1337) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=1337) 			Note: Converting 9 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=1337) 	Stage 2 Generators:
(_dystack pid=1337) 		Fitting FillNaFeatureGenerator...
(_dystack pid=1337) 	Stage 3 Generators:
(_dystack pid=1337) 		Fitting IdentityFeatureGenerator...
(_dystack pid=1337) 	Stage 4 Generators:
(_dystack pid=1337) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=1337) 	Stage 5 Generators:
(_dystack pid=1337) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=1337) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=1337) 		('float', []) : 15 | ['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MAT_PARDA', 'COBERTURA_CRECHE_0_3', 'ESCOLAS_CRECHE_POR_1000_CRIAN', ...]
(_dystack pid=1337) 		('int', [])   :  9 | ['SG_UF_AL', 'SG_UF_BA', 'SG_UF_CE', 'SG_UF_MA', 'SG_UF_PB', ...]
(_dystack pid=1337) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=1337) 		('float', [])     : 15 | ['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MAT_PARDA', 'COBERTURA_CRECHE_0_3', 'ESCOLAS_CRECHE_POR_1000_CRIAN', ...]
(_dystack pid=1337) 		('int', ['bool']) :  9 | ['SG_UF_AL', 'SG_UF_BA', 'SG_UF_CE', 'SG_UF_MA', 'SG_UF_PB', ...]
(_dystack pid=1337) 	0.0s = Fit runtime
(_dystack pid=1337) 	24 features in original data used to generate 24 features in processed data.
(_dystack pid=1337) 	Train Data (Processed) Memory Usage: 0.16 MB (0.0% of available memory)
(_dystack pid=1337) Data preprocessing and feature engineering runtime = 0.02s ...
(_dystack pid=1337) AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
(_dystack pid=1337) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=1337) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=1337) Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=1337) User-specified model hyperparameters to be fit:
(_dystack pid=1337) {
(_dystack pid=1337) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=1337) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=1337) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=1337) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=1337) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=1337) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=1337) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=1337) }
(_dystack pid=1337) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=1337) Fitting 106 L1 models, fit_strategy="sequential" ...
(_dystack pid=1337) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 597.28s of the 896.15s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.28%)
(_dystack pid=1337) 	-0.3087	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.22s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_BAG_L1 ... Training model for up to 594.18s of the 893.04s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.31%)
(_dystack pid=1337) 	-0.317	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.3s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 591.67s of the 890.54s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3214	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.53s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_BAG_L1 ... Training model for up to 590.98s of the 889.85s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.43%)
(_dystack pid=1337) 	-0.3106	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.78s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 588.11s of the 886.97s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3125	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.39s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 587.62s of the 886.48s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=3997) No improvement since epoch 4: early stopping
(_dystack pid=1337) 	-0.3096	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.71s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_BAG_L1 ... Training model for up to 582.78s of the 881.64s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.32%)
(_dystack pid=1337) 	-0.3198	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.02s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 580.34s of the 879.20s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=4954) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=4954)   warnings.warn(
(_ray_fit pid=3999) No improvement since epoch 4: early stopping [repeated 4x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_dystack pid=1337) 	-0.34	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.73s	 = Training   runtime
(_dystack pid=1337) 	0.09s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 572.21s of the 871.08s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.13%)
(_ray_fit pid=4956) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=4956)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.325	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.33s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 567.76s of the 866.62s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.93%)
(_dystack pid=1337) 	-0.313	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.62s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 564.93s of the 863.79s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=6614) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=6614)   warnings.warn(
(_dystack pid=1337) 	-0.3295	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.49s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 557.13s of the 855.99s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.58%)
(_ray_fit pid=6613) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=6613)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3153	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.67s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 554.13s of the 853.00s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=7570) No improvement since epoch 5: early stopping
(_dystack pid=1337) 	-0.3169	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.6s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 546.13s of the 844.99s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.98%)
(_dystack pid=1337) 	-0.3127	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	7.62s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 537.28s of the 836.14s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.16%)
(_ray_fit pid=7572) No improvement since epoch 20: early stopping [repeated 7x across cluster]

(_ray_fit pid=8775) [1000]	valid_set's rmse: 0.306164

(_dystack pid=1337) 	-0.3089	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.65s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 534.39s of the 833.26s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=9239) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=9239)   warnings.warn(
(_dystack pid=1337) 	-0.3315	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.28s	 = Training   runtime
(_dystack pid=1337) 	0.16s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 524.81s of the 823.67s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.20%)
(_ray_fit pid=9242) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=9242)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3193	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.8s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 518.65s of the 817.51s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3126	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.56s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 518.00s of the 816.86s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.38%)
(_dystack pid=1337) 	-0.3129	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.44s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 515.39s of the 814.26s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=10922) No improvement since epoch 6: early stopping
(_dystack pid=1337) 	-0.3064	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	9.31s	 = Training   runtime
(_dystack pid=1337) 	0.09s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 504.85s of the 803.71s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.82%)
(_dystack pid=1337) 	-0.3135	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	12.45s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 491.02s of the 789.88s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_ray_fit pid=10918) No improvement since epoch 0: early stopping
(_dystack pid=1337) 	-0.3201	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.87s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 490.06s of the 788.93s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.09%)
(_dystack pid=1337) 	-0.3103	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	2.19s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 486.73s of the 785.60s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=12617) No improvement since epoch 2: early stopping
(_dystack pid=1337) 	-0.3095	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.65s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 479.75s of the 778.61s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.22%)
(_dystack pid=1337) 	-0.3152	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.89s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 477.57s of the 776.43s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=13572) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=13572)   warnings.warn(
(_ray_fit pid=12616) No improvement since epoch 9: early stopping [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3422	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	17.12s	 = Training   runtime
(_dystack pid=1337) 	0.14s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 459.13s of the 758.00s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.81%)
(_ray_fit pid=13576) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=13576)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3143	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.05s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 456.83s of the 755.69s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=14541) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 2x across cluster]
(_ray_fit pid=14541)   warnings.warn( [repeated 2x across cluster]
(_dystack pid=1337) 	-0.34	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.11s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 449.46s of the 748.32s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.84%)
(_dystack pid=1337) 	-0.3123	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.72s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 446.41s of the 745.27s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=14542) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 6x across cluster]
(_ray_fit pid=14542)   warnings.warn( [repeated 6x across cluster]
(_dystack pid=1337) 	-0.3093	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.44s	 = Training   runtime
(_dystack pid=1337) 	0.11s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 436.67s of the 735.53s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.41%)
(_dystack pid=1337) 	-0.3199	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.43s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 433.84s of the 732.70s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3097	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.41s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 433.34s of the 732.21s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.65%)
(_dystack pid=1337) 	-0.3133	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.33s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 430.78s of the 729.64s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=17410) No improvement since epoch 12: early stopping
(_dystack pid=1337) 	-0.3132	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.84s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 424.53s of the 723.39s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=17902) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=17902)   warnings.warn(
(_ray_fit pid=17404) No improvement since epoch 15: early stopping [repeated 6x across cluster]
(_dystack pid=1337) 	-0.3262	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.22s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 418.00s of the 716.87s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.55%)
(_dystack pid=1337) 	-0.3164	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	2.59s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 414.18s of the 713.04s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=17905) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=17905)   warnings.warn( [repeated 7x across cluster]
(_ray_fit pid=18862) No improvement since epoch 9: early stopping
(_dystack pid=1337) 	-0.3097	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.97s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 408.99s of the 707.86s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.88%)
(_dystack pid=1337) 	-0.3125	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.4s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r156_BAG_L1 ... Training model for up to 404.14s of the 703.00s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=20041) No improvement since epoch 1: early stopping
(_dystack pid=1337) 	-0.3143	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	7.97s	 = Training   runtime
(_dystack pid=1337) 	0.11s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r196_BAG_L1 ... Training model for up to 394.88s of the 693.74s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.57%)

(_ray_fit pid=20548) [1000]	valid_set's rmse: 0.281798 [repeated 5x across cluster]

(_dystack pid=1337) 	-0.309	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.42s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r39_BAG_L1 ... Training model for up to 387.99s of the 686.86s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_ray_fit pid=20047) No improvement since epoch 3: early stopping [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3187	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.71s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r167_BAG_L1 ... Training model for up to 387.20s of the 686.06s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.74%)
(_dystack pid=1337) 	-0.3108	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.09s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r95_BAG_L1 ... Training model for up to 382.89s of the 681.75s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=21727) No improvement since epoch 1: early stopping
(_dystack pid=1337) 	-0.32	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.36s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r41_BAG_L1 ... Training model for up to 376.18s of the 675.05s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=22226) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=22226)   warnings.warn(
(_ray_fit pid=21734) No improvement since epoch 1: early stopping [repeated 5x across cluster]
(_dystack pid=1337) 	-0.3287	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.05s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r98_BAG_L1 ... Training model for up to 369.74s of the 668.60s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.71%)
(_dystack pid=1337) 	-0.3161	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.4s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r15_BAG_L1 ... Training model for up to 363.86s of the 662.72s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.24%)
(_ray_fit pid=22225) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=22225)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3151	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.17s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r158_BAG_L1 ... Training model for up to 361.29s of the 660.15s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=23658) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=23658)   warnings.warn(
(_ray_fit pid=23652) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=23652)   warnings.warn(
(_dystack pid=1337) 	-0.325	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.21s	 = Training   runtime
(_dystack pid=1337) 	0.09s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r86_BAG_L1 ... Training model for up to 351.65s of the 650.51s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.45%)
(_ray_fit pid=23651) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 6x across cluster]
(_ray_fit pid=23651)   warnings.warn( [repeated 6x across cluster]
(_dystack pid=1337) 	-0.3125	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.94s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r37_BAG_L1 ... Training model for up to 341.41s of the 640.27s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=24859) No improvement since epoch 19: early stopping
(_dystack pid=1337) 	-0.3088	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.19s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r197_BAG_L1 ... Training model for up to 334.93s of the 633.79s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=25354) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=25354)   warnings.warn(
(_dystack pid=1337) 	-0.3305	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.81s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r49_BAG_L1 ... Training model for up to 328.72s of the 627.58s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.62%)
(_ray_fit pid=24860) No improvement since epoch 12: early stopping [repeated 2x across cluster]
(_dystack pid=1337) 	-0.3123	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.09s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r49_BAG_L1 ... Training model for up to 326.23s of the 625.09s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_ray_fit pid=25352) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=25352)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3113	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.89s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r143_BAG_L1 ... Training model for up to 325.24s of the 624.10s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.62%)
(_dystack pid=1337) 	-0.3169	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.9s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r127_BAG_L1 ... Training model for up to 322.12s of the 620.98s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.316	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.89s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r134_BAG_L1 ... Training model for up to 321.16s of the 620.02s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=27043) No improvement since epoch 2: early stopping
(_ray_fit pid=27047) No improvement since epoch 20: early stopping [repeated 3x across cluster]
(_dystack pid=1337) 	-0.309	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	23.17s	 = Training   runtime
(_dystack pid=1337) 	0.16s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r34_BAG_L1 ... Training model for up to 296.72s of the 595.58s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3134	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.66s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r94_BAG_L1 ... Training model for up to 295.99s of the 594.86s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.17%)
(_dystack pid=1337) 	-0.3098	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.15s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r143_BAG_L1 ... Training model for up to 293.60s of the 592.46s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=28049) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=28049)   warnings.warn(
(_ray_fit pid=27046) No improvement since epoch 25: early stopping [repeated 3x across cluster]
(_dystack pid=1337) 	-0.3252	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.5s	 = Training   runtime
(_dystack pid=1337) 	0.12s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r128_BAG_L1 ... Training model for up to 283.78s of the 582.64s of remaining time.
(_ray_fit pid=28053) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=28053)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.75%)
(_dystack pid=1337) 	-0.312	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.72s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r111_BAG_L1 ... Training model for up to 275.65s of the 574.51s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_dystack pid=1337) 	-0.3078	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	9.15s	 = Training   runtime
(_dystack pid=1337) 	0.13s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r31_BAG_L1 ... Training model for up to 265.05s of the 563.91s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=29749) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=29749)   warnings.warn(
(_dystack pid=1337) 	-0.3288	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.53s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r4_BAG_L1 ... Training model for up to 258.10s of the 556.96s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3128	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.62s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r65_BAG_L1 ... Training model for up to 257.41s of the 556.27s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_dystack pid=1337) 	-0.3193	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.11s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r88_BAG_L1 ... Training model for up to 252.14s of the 551.00s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.04%)
(_ray_fit pid=29752) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=29752)   warnings.warn( [repeated 7x across cluster]
(_ray_fit pid=30748) No improvement since epoch 2: early stopping
(_dystack pid=1337) 	-0.3234	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.26s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r30_BAG_L1 ... Training model for up to 247.47s of the 546.34s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.85%)

(_ray_fit pid=31228) [1000]	valid_set's rmse: 0.282139 [repeated 6x across cluster]

(_dystack pid=1337) 	-0.3086	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.82s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r49_BAG_L1 ... Training model for up to 244.00s of the 542.86s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.35%)
(_dystack pid=1337) 	-0.3181	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.61s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r5_BAG_L1 ... Training model for up to 241.15s of the 540.02s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.47%)
(_ray_fit pid=30744) No improvement since epoch 4: early stopping [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3127	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.11s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r87_BAG_L1 ... Training model for up to 238.58s of the 537.44s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=32865) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=32865)   warnings.warn(
(_dystack pid=1337) 	-0.3275	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.84s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r71_BAG_L1 ... Training model for up to 231.32s of the 530.18s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=33363) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 8x across cluster]
(_ray_fit pid=33363)   warnings.warn( [repeated 8x across cluster]
(_dystack pid=1337) 	-0.3299	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.89s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r143_BAG_L1 ... Training model for up to 225.84s of the 524.70s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=8.58%)
(_dystack pid=1337) 	-0.3113	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.05s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r178_BAG_L1 ... Training model for up to 221.19s of the 520.05s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_ray_fit pid=33357) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=33357)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3098	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.88s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r166_BAG_L1 ... Training model for up to 220.23s of the 519.09s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3169	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.91s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r31_BAG_L1 ... Training model for up to 219.23s of the 518.09s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.17%)
(_dystack pid=1337) 	-0.3148	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.94s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r185_BAG_L1 ... Training model for up to 217.15s of the 516.01s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=35054) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=35054)   warnings.warn(
(_ray_fit pid=35050) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=35050)   warnings.warn(
(_dystack pid=1337) 	-0.318	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.04s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r160_BAG_L1 ... Training model for up to 210.74s of the 509.60s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.04%)
(_dystack pid=1337) 	-0.3049	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.11s	 = Training   runtime
(_dystack pid=1337) 	0.1s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r60_BAG_L1 ... Training model for up to 204.00s of the 502.86s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.54%)
(_ray_fit pid=35055) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 6x across cluster]
(_ray_fit pid=35055)   warnings.warn( [repeated 6x across cluster]
(_dystack pid=1337) 	-0.3122	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.22s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r15_BAG_L1 ... Training model for up to 201.36s of the 500.22s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.317	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.98s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r135_BAG_L1 ... Training model for up to 200.30s of the 499.17s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.93%)
(_dystack pid=1337) 	-0.3135	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.17s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r22_BAG_L1 ... Training model for up to 197.94s of the 496.80s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.21%)
(_dystack pid=1337) 	-0.316	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.02s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r69_BAG_L1 ... Training model for up to 195.62s of the 494.48s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_dystack pid=1337) 	-0.3077	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.75s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r6_BAG_L1 ... Training model for up to 189.51s of the 488.37s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.21%)
(_dystack pid=1337) 	-0.3121	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.47s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r138_BAG_L1 ... Training model for up to 186.63s of the 485.49s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=38870) No improvement since epoch 9: early stopping
(_dystack pid=1337) 	-0.3119	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.93s	 = Training   runtime
(_dystack pid=1337) 	0.11s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r121_BAG_L1 ... Training model for up to 176.29s of the 475.15s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.24%)
(_dystack pid=1337) 	-0.3165	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	2.87s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r172_BAG_L1 ... Training model for up to 172.06s of the 470.92s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=38871) No improvement since epoch 24: early stopping [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3096	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.1s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r180_BAG_L1 ... Training model for up to 166.61s of the 465.47s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=9.19%)
(_ray_fit pid=39839) No improvement since epoch 8: early stopping [repeated 3x across cluster]
(_dystack pid=1337) 	-0.3127	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.01s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r76_BAG_L1 ... Training model for up to 160.08s of the 458.94s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
(_ray_fit pid=41036) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=41036)   warnings.warn(
(_dystack pid=1337) 	-0.3306	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.26s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r197_BAG_L1 ... Training model for up to 154.48s of the 453.34s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3125	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.03s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r121_BAG_L1 ... Training model for up to 153.35s of the 452.21s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
(_ray_fit pid=41543) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 8x across cluster]
(_ray_fit pid=41543)   warnings.warn( [repeated 8x across cluster]
(_dystack pid=1337) 	-0.3365	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	10.1s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r127_BAG_L1 ... Training model for up to 142.06s of the 440.92s of remaining time.
(_ray_fit pid=41545) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=41545)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_dystack pid=1337) 	-0.31	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.54s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r16_BAG_L1 ... Training model for up to 137.17s of the 436.03s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3214	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.17s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r194_BAG_L1 ... Training model for up to 135.91s of the 434.78s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_dystack pid=1337) 	-0.3074	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.12s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r12_BAG_L1 ... Training model for up to 130.63s of the 429.49s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=8.95%)
(_dystack pid=1337) 	-0.3123	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.71s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r135_BAG_L1 ... Training model for up to 124.28s of the 423.14s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
(_ray_fit pid=43745) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=43745)   warnings.warn(
(_dystack pid=1337) 	-0.3311	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	9.84s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r4_BAG_L1 ... Training model for up to 113.07s of the 411.93s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=43740) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=43740)   warnings.warn( [repeated 7x across cluster]
(_ray_fit pid=44236) No improvement since epoch 15: early stopping
(_dystack pid=1337) 	-0.3085	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.79s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r126_BAG_L1 ... Training model for up to 107.94s of the 406.80s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3113	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.95s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r36_BAG_L1 ... Training model for up to 106.91s of the 405.77s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
(_ray_fit pid=44744) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=44744)   warnings.warn(
(_ray_fit pid=44242) No improvement since epoch 1: early stopping
(_dystack pid=1337) 	-0.3303	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.26s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r100_BAG_L1 ... Training model for up to 100.49s of the 399.36s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
(_ray_fit pid=45238) No improvement since epoch 0: early stopping

(_ray_fit pid=50514) [1000]	valid_set's rmse: 0.331164
(_ray_fit pid=50513) [1000]	valid_set's rmse: 0.278166
(_ray_fit pid=50513) [5000]	valid_set's rmse: 0.274232 [repeated 18x across cluster]
(_ray_fit pid=50513) [9000]	valid_set's rmse: 0.274227 [repeated 14x across cluster]

(_dystack pid=1337) 	-0.2969	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	13.36s	 = Training   runtime
(_dystack pid=1337) 	0.4s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_BAG_L2 ... Training model for up to 317.21s of the 317.12s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.58%)
(_dystack pid=1337) 	-0.3092	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.58s	 = Training   runtime
(_dystack pid=1337) 	0.01s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 314.38s of the 314.29s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3106	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.95s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_BAG_L2 ... Training model for up to 313.34s of the 313.25s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.83%)
(_dystack pid=1337) 	-0.3043	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.75s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 308.42s of the 308.33s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3032	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.39s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 307.93s of the 307.84s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
(_ray_fit pid=52197) No improvement since epoch 4: early stopping
(_dystack pid=1337) 	-0.3088	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.94s	 = Training   runtime
(_dystack pid=1337) 	0.09s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_BAG_L2 ... Training model for up to 302.70s of the 302.62s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.10%)
(_dystack pid=1337) 	-0.3094	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.97s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 299.22s of the 299.13s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.06%)
(_ray_fit pid=52199) No improvement since epoch 5: early stopping [repeated 4x across cluster]
(_ray_fit pid=53145) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=53145)   warnings.warn(
(_dystack pid=1337) 	-0.3202	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.6s	 = Training   runtime
(_dystack pid=1337) 	0.13s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 293.30s of the 293.21s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.87%)
(_dystack pid=1337) 	-0.3185	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.99s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r177_BAG_L2 ... Training model for up to 286.94s of the 286.85s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.19%)
(_ray_fit pid=53151) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=53151)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3035	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.97s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r79_BAG_L2 ... Training model for up to 281.76s of the 281.67s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.06%)
(_ray_fit pid=54819) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=54819)   warnings.warn(
(_dystack pid=1337) 	-0.3281	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.91s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r131_BAG_L2 ... Training model for up to 274.57s of the 274.48s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.06%)

(_ray_fit pid=55309) [1000]	valid_set's rmse: 0.289847 [repeated 2x across cluster]
(_ray_fit pid=55309) [4000]	valid_set's rmse: 0.288725 [repeated 5x across cluster]

(_dystack pid=1337) 	-0.3077	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	9.56s	 = Training   runtime
(_dystack pid=1337) 	0.09s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r191_BAG_L2 ... Training model for up to 263.49s of the 263.40s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
(_ray_fit pid=54817) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=54817)   warnings.warn( [repeated 7x across cluster]
(_ray_fit pid=55790) No improvement since epoch 1: early stopping
(_dystack pid=1337) 	-0.3004	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	7.05s	 = Training   runtime
(_dystack pid=1337) 	0.11s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r9_BAG_L2 ... Training model for up to 255.24s of the 255.16s of remaining time.
(_dystack pid=1337) 	Memory not enough to fit 8 folds in parallel. Will train 4 folds in parallel instead (Estimated 11.22% memory usage per fold, 44.88%/80.00% total).
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (4 workers, per: cpus=4, gpus=0, memory=11.22%)
(_dystack pid=1337) 	-0.3024	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	25.36s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r96_BAG_L2 ... Training model for up to 228.66s of the 228.58s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.33%)
(_ray_fit pid=55787) No improvement since epoch 6: early stopping [repeated 4x across cluster]

(_ray_fit pid=57033) [1000]	valid_set's rmse: 0.296351
(_ray_fit pid=57035) [1000]	valid_set's rmse: 0.314071

(_dystack pid=1337) 	-0.3021	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	4.31s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r22_BAG_L2 ... Training model for up to 222.82s of the 222.73s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.06%)
(_ray_fit pid=57504) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=57504)   warnings.warn(
(_dystack pid=1337) 	-0.3334	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.71s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r33_BAG_L2 ... Training model for up to 214.95s of the 214.87s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.12%)
(_ray_fit pid=57501) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=57501)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3095	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	9.46s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r42_BAG_L2 ... Training model for up to 204.14s of the 204.06s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3057	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.58s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r137_BAG_L2 ... Training model for up to 203.47s of the 203.38s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.39%)
(_dystack pid=1337) 	-0.3016	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	2.97s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r102_BAG_L2 ... Training model for up to 199.23s of the 199.14s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
(_ray_fit pid=59195) No improvement since epoch 8: early stopping
(_dystack pid=1337) 	-0.3054	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	10.81s	 = Training   runtime
(_dystack pid=1337) 	0.14s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r13_BAG_L2 ... Training model for up to 187.08s of the 187.00s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=9.77%)
(_dystack pid=1337) 	-0.3044	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	24.25s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: RandomForest_r195_BAG_L2 ... Training model for up to 161.45s of the 161.36s of remaining time.
(_ray_fit pid=59192) No improvement since epoch 7: early stopping
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3104	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.95s	 = Training   runtime
(_dystack pid=1337) 	0.06s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r188_BAG_L2 ... Training model for up to 160.40s of the 160.32s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.08%)

(_ray_fit pid=60447) [1000]	valid_set's rmse: 0.286658 [repeated 10x across cluster]
(_ray_fit pid=60445) [2000]	valid_set's rmse: 0.284905 [repeated 9x across cluster]
(_ray_fit pid=60442) [4000]	valid_set's rmse: 0.309318 [repeated 7x across cluster]
(_ray_fit pid=60441) [6000]	valid_set's rmse: 0.290396 [repeated 6x across cluster]
(_ray_fit pid=60445) [6000]	valid_set's rmse: 0.2849 [repeated 6x across cluster]
(_ray_fit pid=60445) [8000]	valid_set's rmse: 0.2849 [repeated 5x across cluster]

(_dystack pid=1337) 	-0.3004	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	37.66s	 = Training   runtime
(_dystack pid=1337) 	0.89s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r145_BAG_L2 ... Training model for up to 120.33s of the 120.24s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
(_ray_fit pid=60949) No improvement since epoch 3: early stopping
(_dystack pid=1337) 	-0.3056	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.01s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r89_BAG_L2 ... Training model for up to 113.11s of the 113.03s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.80%)
(_dystack pid=1337) 	-0.3059	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.41s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r30_BAG_L2 ... Training model for up to 110.45s of the 110.36s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.06%)
(_ray_fit pid=61907) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=61907)   warnings.warn(
(_ray_fit pid=60947) No improvement since epoch 2: early stopping [repeated 3x across cluster]
(_dystack pid=1337) 	-0.3301	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.98s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r130_BAG_L2 ... Training model for up to 100.13s of the 100.04s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.56%)
(_ray_fit pid=61904) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=61904)   warnings.warn( [repeated 7x across cluster]
(_dystack pid=1337) 	-0.3052	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	1.1s	 = Training   runtime
(_dystack pid=1337) 	0.02s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r86_BAG_L2 ... Training model for up to 97.79s of the 97.70s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.06%)
(_ray_fit pid=62872) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 3x across cluster]
(_ray_fit pid=62872)   warnings.warn( [repeated 3x across cluster]
(_dystack pid=1337) 	-0.3376	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.94s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r50_BAG_L2 ... Training model for up to 87.46s of the 87.37s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.40%)
(_ray_fit pid=62874) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 5x across cluster]
(_ray_fit pid=62874)   warnings.warn( [repeated 5x across cluster]
(_dystack pid=1337) 	-0.3	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	33.62s	 = Training   runtime
(_dystack pid=1337) 	0.04s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r11_BAG_L2 ... Training model for up to 52.64s of the 52.55s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
(_ray_fit pid=64091) No improvement since epoch 8: early stopping
(_dystack pid=1337) 	-0.3034	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	8.63s	 = Training   runtime
(_dystack pid=1337) 	0.13s	 = Validation runtime
(_dystack pid=1337) Fitting model: XGBoost_r194_BAG_L2 ... Training model for up to 42.81s of the 42.72s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.83%)
(_dystack pid=1337) 	-0.3123	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	2.97s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: ExtraTrees_r172_BAG_L2 ... Training model for up to 38.36s of the 38.28s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
(_dystack pid=1337) 	-0.3045	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.33s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r69_BAG_L2 ... Training model for up to 37.96s of the 37.87s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.28%)
(_dystack pid=1337) 	-0.3038	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	2.61s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r103_BAG_L2 ... Training model for up to 34.22s of the 34.13s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.10%)
(_ray_fit pid=65768) No improvement since epoch 1: early stopping
(_dystack pid=1337) 	-0.3048	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	5.3s	 = Training   runtime
(_dystack pid=1337) 	0.07s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetTorch_r14_BAG_L2 ... Training model for up to 27.70s of the 27.62s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.07%)
(_ray_fit pid=66254) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
(_ray_fit pid=66254)   warnings.warn(
(_ray_fit pid=65767) No improvement since epoch 16: early stopping [repeated 3x across cluster]
(_dystack pid=1337) 	-0.3143	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.95s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: LightGBM_r161_BAG_L2 ... Training model for up to 22.30s of the 22.22s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=4.93%)

(_ray_fit pid=66741) [1000]	valid_set's rmse: 0.287952 [repeated 2x across cluster]

(_dystack pid=1337) 	-0.3071	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	6.03s	 = Training   runtime
(_dystack pid=1337) 	0.05s	 = Validation runtime
(_dystack pid=1337) Fitting model: NeuralNetFastAI_r143_BAG_L2 ... Training model for up to 14.76s of the 14.68s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.09%)
(_ray_fit pid=66256) /home/guilherme_fernandes/anaconda3/envs/aprendizagem_automatica/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning. [repeated 7x across cluster]
(_ray_fit pid=66256)   warnings.warn( [repeated 7x across cluster]
(_ray_fit pid=67215) No improvement since epoch 5: early stopping
(_dystack pid=1337) 	-0.3064	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	3.86s	 = Training   runtime
(_dystack pid=1337) 	0.08s	 = Validation runtime
(_dystack pid=1337) Fitting model: CatBoost_r70_BAG_L2 ... Training model for up to 9.69s of the 9.61s of remaining time.
(_dystack pid=1337) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=8.24%)
(_dystack pid=1337) 	-0.3027	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	7.3s	 = Training   runtime
(_dystack pid=1337) 	0.03s	 = Validation runtime
(_ray_fit pid=67220) No improvement since epoch 5: early stopping [repeated 2x across cluster]
(_dystack pid=1337) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 0.69s of remaining time.
(_dystack pid=1337) 	Fitting 1 model on all data | Fitting with cpus=16, gpus=0, mem=0.0/7.8 GB
(_dystack pid=1337) 	Ensemble Weights: {'LightGBMXT_BAG_L2': 0.409, 'NeuralNetFastAI_r191_BAG_L2': 0.364, 'CatBoost_r50_BAG_L2': 0.182, 'NeuralNetFastAI_r11_BAG_L2': 0.045}
(_dystack pid=1337) 	-0.2911	 = Validation score   (-root_mean_squared_error)
(_dystack pid=1337) 	0.01s	 = Training   runtime
(_dystack pid=1337) 	0.0s	 = Validation runtime
(_dystack pid=1337) AutoGluon training complete, total runtime = 895.5s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 137.7 rows/s (159 batch size)
(_dystack pid=1337) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/guilherme_fernandes/Aprendizagem_Autom-tica_UFC_2026.1/criancas_creche/Notebooks/autogluon_regression/ds_sub_fit/sub_fit_ho")
(_dystack pid=1337) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                           model  score_holdout  score_val              eval_metric  pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0    NeuralNetFastAI_r100_BAG_L1      -0.312673  -0.312996  root_mean_squared_error        0.087670       0.174851   19.899203                 0.087670                0.174851          19.899203            1       True         97
1            LightGBM_r42_BAG_L1      -0.315617  -0.311503  root_mean_squared_error        0.010208       0.010314    1.318192                 0.010208                0.010314           1.318192            1       True        104
2           LightGBM_r188_BAG_L1      -0.315919  -0.310252  root_mean_squared_error        0.032660       0.012276    2.188587                 0.032660                0.012276           2.188587            1       True         23
3            LightGBM_r94_BAG_L1      -0.316880  -0.309771  root_mean_squared_error        0.042498       0.016970    1.145802                 0.042498                0.016970           1.145802            1       True         57
4           LightGBM_r196_BAG_L1      -0.317021  -0.309014  root_mean_squared_error        0.094454       0.074528    5.423074                 0.094454                0.074528           5.423074            1       True         40
5            CatBoost_r13_BAG_L2      -0.317330  -0.304428  root_mean_squared_error        0.962478       0.731220   64.509910                 0.015397                0.055506          24.252677            2       True        128
6    NeuralNetFastAI_r172_BAG_L1      -0.317417  -0.309573  root_mean_squared_error        0.041036       0.080551    4.095613                 0.041036                0.080551           4.095613            1       True         84
7     NeuralNetFastAI_r69_BAG_L1      -0.317495  -0.307672  root_mean_squared_error        0.055308       0.072810    4.745716                 0.055308                0.072810           4.745716            1       True         80
8    NeuralNetFastAI_r191_BAG_L1      -0.317627  -0.316893  root_mean_squared_error        0.048369       0.079099    6.597562                 0.048369                0.079099           6.597562            1       True         13
9    NeuralNetFastAI_r138_BAG_L1      -0.317763  -0.311897  root_mean_squared_error        0.059167       0.105797    8.926948                 0.059167                0.105797           8.926948            1       True         82
10           LightGBM_r30_BAG_L1      -0.317893  -0.308591  root_mean_squared_error        0.026565       0.025351    1.816137                 0.026565                0.025351           1.816137            1       True         65
11           LightGBM_r96_BAG_L1      -0.318120  -0.308864  root_mean_squared_error        0.023696       0.039280    1.645085                 0.023696                0.039280           1.645085            1       True         15
12             LightGBMXT_BAG_L1      -0.318165  -0.308669  root_mean_squared_error        0.102708       0.009575    1.222566                 0.102708                0.009575           1.222566            1       True          1
13           CatBoost_r86_BAG_L1      -0.318207  -0.312459  root_mean_squared_error        0.016494       0.012629    8.936324                 0.016494                0.012629           8.936324            1       True         48
14        ExtraTrees_r178_BAG_L1      -0.318366  -0.309820  root_mean_squared_error        0.043497       0.059084    0.884233                 0.043497                0.059084           0.884233            1       True         71
15   NeuralNetFastAI_r103_BAG_L1      -0.318464  -0.313201  root_mean_squared_error        0.065508       0.065431    4.842224                 0.065508                0.065431           4.842224            1       True         34
16               CatBoost_BAG_L2      -0.318717  -0.304258  root_mean_squared_error        0.957190       0.717659   44.009861                 0.010109                0.041945           3.752629            2       True        111
17         ExtraTrees_r42_BAG_L2      -0.318774  -0.305740  root_mean_squared_error        0.992170       0.737228   40.835585                 0.045089                0.061514           0.578353            2       True        125
18     NeuralNetFastAI_r4_BAG_L1      -0.318827  -0.308516  root_mean_squared_error        0.045035       0.067093    3.786716                 0.045035                0.067093           3.786716            1       True         94
19    NeuralNetFastAI_r37_BAG_L1      -0.318850  -0.308827  root_mean_squared_error        0.076430       0.061606    5.191737                 0.076430                0.061606           5.191737            1       True         49
20    NeuralNetFastAI_r11_BAG_L1      -0.318875  -0.309276  root_mean_squared_error        0.058370       0.111119    8.436018                 0.058370                0.111119           8.436018            1       True         30
21           CatBoost_r13_BAG_L1      -0.318982  -0.313487  root_mean_squared_error        0.013418       0.010864   12.451597                 0.013418                0.010864          12.451597            1       True         21
22           CatBoost_r69_BAG_L2      -0.318992  -0.303819  root_mean_squared_error        0.957352       0.709484   42.865258                 0.010271                0.033771           2.608026            2       True        140
23         ExtraTrees_r42_BAG_L1      -0.319018  -0.312608  root_mean_squared_error        0.051235       0.058672    0.564351                 0.051235                0.058672           0.564351            1       True         18
24               CatBoost_BAG_L1      -0.319078  -0.310601  root_mean_squared_error        0.143387       0.008764    1.783794                 0.143387                0.008764           1.783794            1       True          4
25          CatBoost_r177_BAG_L2      -0.319195  -0.303516  root_mean_squared_error        0.962360       0.718682   44.231202                 0.015279                0.042968           3.973969            2       True        117
26          LightGBM_r161_BAG_L1      -0.319266  -0.316374  root_mean_squared_error        0.022148       0.023471    2.591389                 0.022148                0.023471           2.591389            1       True         36
27          CatBoost_r143_BAG_L1      -0.319280  -0.311325  root_mean_squared_error        0.009614       0.011321    3.047298                 0.009614                0.011321           3.047298            1       True         70
28          CatBoost_r137_BAG_L2      -0.319295  -0.301613  root_mean_squared_error        0.958912       0.706043   43.222975                 0.011831                0.030329           2.965742            2       True        126
29            XGBoost_r49_BAG_L1      -0.319420  -0.318078  root_mean_squared_error        0.052552       0.029928    1.607055                 0.052552                0.029928           1.607055            1       True         66
30          CatBoost_r167_BAG_L1      -0.319694  -0.310835  root_mean_squared_error        0.008391       0.010478    3.093577                 0.008391                0.010478           3.093577            1       True         42
31   NeuralNetFastAI_r102_BAG_L2      -0.319739  -0.305402  root_mean_squared_error        1.030701       0.814865   51.065090                 0.083620                0.139151          10.807858            2       True        127
32   NeuralNetFastAI_r156_BAG_L1      -0.319863  -0.314255  root_mean_squared_error        0.078683       0.107508    7.968043                 0.078683                0.107508           7.968043            1       True         39
33           CatBoost_r12_BAG_L1      -0.319908  -0.312301  root_mean_squared_error        0.013355       0.009836    4.711964                 0.013355                0.009836           4.711964            1       True         92
34           LightGBM_r96_BAG_L2      -0.319968  -0.302138  root_mean_squared_error        0.998682       0.757820   44.563524                 0.051601                0.082106           4.306292            2       True        122
35   NeuralNetFastAI_r145_BAG_L1      -0.320029  -0.309510  root_mean_squared_error        0.059929       0.081894    5.646240                 0.059929                0.081894           5.646240            1       True         24
36        ExtraTrees_r126_BAG_L1      -0.320094  -0.311348  root_mean_squared_error        0.041949       0.058960    0.953361                 0.041949                0.058960           0.953361            1       True         95
37        ExtraTrees_r172_BAG_L2      -0.320117  -0.304490  root_mean_squared_error        0.990242       0.729936   40.592127                 0.043160                0.054222           0.334894            2       True        139
38            XGBoost_r31_BAG_L1      -0.320181  -0.314775  root_mean_squared_error        0.089251       0.023462    0.937277                 0.089251                0.023462           0.937277            1       True         73
39           CatBoost_r70_BAG_L2      -0.320195  -0.302684  root_mean_squared_error        0.961393       0.708991   47.561023                 0.014312                0.033277           7.303790            2       True        145
40            CatBoost_r9_BAG_L1      -0.320278  -0.312677  root_mean_squared_error        0.014353       0.008872    7.623382                 0.014353                0.008872           7.623382            1       True         14
41          CatBoost_r198_BAG_L1      -0.320349  -0.312544  root_mean_squared_error        0.011225       0.009290    1.795185                 0.011225                0.009290           1.795185            1       True         99
42           CatBoost_r69_BAG_L1      -0.320375  -0.313303  root_mean_squared_error        0.009768       0.007483    1.330785                 0.009768                0.007483           1.330785            1       True         33
43            XGBoost_r22_BAG_L1      -0.320381  -0.315980  root_mean_squared_error        0.038315       0.024476    1.021803                 0.038315                0.024476           1.021803            1       True         79
44           CatBoost_r60_BAG_L1      -0.320482  -0.312238  root_mean_squared_error        0.013399       0.008277    1.217733                 0.013399                0.008277           1.217733            1       True         76
45          LightGBMLarge_BAG_L2      -0.320614  -0.318515  root_mean_squared_error        0.964774       0.692277   45.250808                 0.017693                0.016563           4.993576            2       True        116
46            XGBoost_r33_BAG_L1      -0.320692  -0.319323  root_mean_squared_error        0.060035       0.035723    4.798538                 0.060035                0.035723           4.798538            1       True         17
47           WeightedEnsemble_L2      -0.320747  -0.301557  root_mean_squared_error        0.468672       0.352851   28.896838                 0.002426                0.000242           0.007570            2       True        107
48   NeuralNetFastAI_r103_BAG_L2      -0.320865  -0.304843  root_mean_squared_error        0.991746       0.748530   45.558460                 0.044665                0.072816           5.301227            2       True        141
49          LightGBM_r121_BAG_L1      -0.320879  -0.316462  root_mean_squared_error        0.024230       0.025867    2.869688                 0.024230                0.025867           2.869688            1       True         83
50   NeuralNetFastAI_r143_BAG_L2      -0.320916  -0.306387  root_mean_squared_error        0.993119       0.755802   44.120004                 0.046037                0.080089           3.862772            2       True        144
51        ExtraTrees_r172_BAG_L1      -0.320926  -0.309739  root_mean_squared_error        0.044675       0.063042    0.412960                 0.044675                0.063042           0.412960            1       True         32
52          LightGBM_r131_BAG_L1      -0.321003  -0.315287  root_mean_squared_error        0.015110       0.018160    1.668259                 0.015110                0.018160           1.668259            1       True         12
53          LightGBM_r130_BAG_L1      -0.321020  -0.314309  root_mean_squared_error        0.006146       0.008470    1.051937                 0.006146                0.008470           1.051937            1       True         27
54          CatBoost_r177_BAG_L1      -0.321061  -0.313030  root_mean_squared_error        0.012630       0.008697    1.616463                 0.012630                0.008697           1.616463            1       True         10
55          CatBoost_r128_BAG_L1      -0.321071  -0.312007  root_mean_squared_error        0.019557       0.011865    6.715849                 0.019557                0.011865           6.715849            1       True         59
56   NeuralNetFastAI_r102_BAG_L1      -0.321182  -0.306394  root_mean_squared_error        0.090166       0.089752    9.307981                 0.090166                0.089752           9.307981            1       True         20
57            CatBoost_r6_BAG_L1      -0.321184  -0.312105  root_mean_squared_error        0.008991       0.008129    1.470846                 0.008991                0.008129           1.470846            1       True         81
58            XGBoost_r33_BAG_L2      -0.321200  -0.309516  root_mean_squared_error        1.006427       0.722554   49.721837                 0.059346                0.046840           9.464604            2       True        124
59         ExtraTrees_r49_BAG_L1      -0.321216  -0.311318  root_mean_squared_error        0.048173       0.068627    0.889852                 0.048173                0.068627           0.889852            1       True         52
60            XGBoost_r89_BAG_L2      -0.321227  -0.305942  root_mean_squared_error        0.978607       0.707897   41.665888                 0.031526                0.032183           1.408656            2       True        132
61          LightGBM_r188_BAG_L2      -0.321231  -0.300440  root_mean_squared_error        1.769718       1.567084   77.919342                 0.822637                0.891371          37.662110            2       True        130
62            XGBoost_r98_BAG_L1      -0.321333  -0.316071  root_mean_squared_error        0.077077       0.074672    4.399117                 0.077077                0.074672           4.399117            1       True         45
63          ExtraTreesMSE_BAG_L2      -0.321355  -0.303161  root_mean_squared_error        1.007776       0.739569   40.651361                 0.060695                0.063855           0.394129            2       True        112
64           WeightedEnsemble_L3      -0.321377  -0.291126  root_mean_squared_error        1.328320       1.356290  102.918083                 0.001358                0.000219           0.007915            3       True        146
65    NeuralNetFastAI_r95_BAG_L1      -0.321404  -0.319962  root_mean_squared_error        0.057961       0.076543    5.364530                 0.057961                0.076543           5.364530            1       True         43
66          CatBoost_r163_BAG_L1      -0.321639  -0.312510  root_mean_squared_error        0.008130       0.007437    1.372034                 0.008130                0.007437           1.372034            1       True         98
67    NeuralNetFastAI_r11_BAG_L2      -0.321785  -0.303384  root_mean_squared_error        1.007284       0.806450   48.884732                 0.060203                0.130736           8.627499            2       True        137
68            XGBoost_r34_BAG_L1      -0.321861  -0.317463  root_mean_squared_error        0.066737       0.061118    3.106188                 0.066737                0.061118           3.106188            1       True        103
69                XGBoost_BAG_L2      -0.321883  -0.309376  root_mean_squared_error        0.992871       0.710426   42.229627                 0.045790                0.034712           1.972394            2       True        114
70   NeuralNetFastAI_r134_BAG_L1      -0.321885  -0.308982  root_mean_squared_error        0.138846       0.155681   23.165872                 0.138846                0.155681          23.165872            1       True         55
71        NeuralNetFastAI_BAG_L1      -0.321971  -0.309623  root_mean_squared_error        0.429429       0.068831    3.708750                 0.429429                0.068831           3.708750            1       True          6
72           CatBoost_r70_BAG_L1      -0.322012  -0.312461  root_mean_squared_error        0.013811       0.009725    3.395152                 0.013811                0.009725           3.395152            1       True         38

In [15]:
leaderboard

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost_r69_BAG_L1,-0.305733,-0.310358,root_mean_squared_error,0.010092,0.006946,1.518379,0.010092,0.006946,1.518379,1,True,33
1,NeuralNetFastAI_r160_BAG_L1,-0.306288,-0.307994,root_mean_squared_error,0.116079,0.094204,5.070493,0.116079,0.094204,5.070493,1,True,75
2,LightGBM_r96_BAG_L1,-0.306805,-0.309427,root_mean_squared_error,0.024602,0.036252,1.041376,0.024602,0.036252,1.041376,1,True,15
3,XGBoost_r89_BAG_L1,-0.306846,-0.313833,root_mean_squared_error,0.032134,0.024283,0.903103,0.032134,0.024283,0.903103,1,True,25
4,CatBoost_r60_BAG_L1,-0.306888,-0.310666,root_mean_squared_error,0.016732,0.006956,2.009156,0.016732,0.006956,2.009156,1,True,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,NeuralNetTorch_r31_BAG_L1,-0.337604,-0.332468,root_mean_squared_error,0.062397,0.065753,5.637991,0.062397,0.065753,5.637991,1,True,61
103,NeuralNetTorch_r76_BAG_L1,-0.339503,-0.329801,root_mean_squared_error,0.051714,0.067739,4.625883,0.051714,0.067739,4.625883,1,True,86
104,NeuralNetTorch_r19_BAG_L1,-0.340220,-0.331017,root_mean_squared_error,0.045204,0.066069,4.087522,0.045204,0.066069,4.087522,1,True,101
105,NeuralNetTorch_r89_BAG_L1,-0.341080,-0.336418,root_mean_squared_error,0.066197,0.105615,8.532468,0.066197,0.105615,8.532468,1,True,106
106,NeuralNetTorch_r86_BAG_L1,-0.342045,-0.339542,root_mean_squared_error,0.104718,0.055575,7.596215,0.104718,0.055575,7.596215,1,True,28

In [16]:
metrics

{'rmse': np.float64(0.30747117806625385),
 'mae': 0.23923081665285262,
 'r2': 0.26678992693168113}

In [17]:
leaderboard.head()

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost_r69_BAG_L1,-0.305733,-0.310358,root_mean_squared_error,0.010092,0.006946,1.518379,0.010092,0.006946,1.518379,1,True,33
1,NeuralNetFastAI_r160_BAG_L1,-0.306288,-0.307994,root_mean_squared_error,0.116079,0.094204,5.070493,0.116079,0.094204,5.070493,1,True,75
2,LightGBM_r96_BAG_L1,-0.306805,-0.309427,root_mean_squared_error,0.024602,0.036252,1.041376,0.024602,0.036252,1.041376,1,True,15
3,XGBoost_r89_BAG_L1,-0.306846,-0.313833,root_mean_squared_error,0.032134,0.024283,0.903103,0.032134,0.024283,0.903103,1,True,25
4,CatBoost_r60_BAG_L1,-0.306888,-0.310666,root_mean_squared_error,0.016732,0.006956,2.009156,0.016732,0.006956,2.009156,1,True,76

In [18]:
leaderboard.to_csv('leaderboard_automl.csv', index=False)